In [3]:
!nvidia-smi

Fri Sep  5 18:51:18 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.05              Driver Version: 560.35.05      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        On  |   00000000:CE:00.0 Off |                  N/A |
| 31%   34C    P8             34W /  350W |       4MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [1]:
!python -u AutomaticPipeline/AutoPipeline.py

/home3/s20245649/.conda/envs/speechcraft/lib/python3.9/site-packages/transformers/modeling_utils.py:3437: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
funasr version: 1.1.16.
Check update of funasr, and it would cost few times. You may disable it by set `disable_update=True` in AutoModel
New version is available: 1.2.7.
Please use the command "pip install -U funasr" to upgrade.
Fetching 9 files: 100%|███████████████████████| 9/9 [00:00<00:00, 177224.11it/s]
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.0.0.weight, /home3/s20245649/.cache/huggingface/hub/models--emotion2vec--emotion2vec_plus_large/snapshots/6c303ba987b86b93193de93e34bb2b077a6bedc4/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.0.0.bias, /home3/s20245649/.cache/huggingface/hub/models--emotion2vec--emotion2vec_plus_large/snapshots/6c303ba987b86b93193de93e34bb2b077a6bedc4/mod

In [3]:
!python -u AutomaticPipeline/Clustering.py

In [2]:
import librosa


wav, sr = librosa.load("/data1/movie/CMD/processed_wavs/audio_segments_bef_persona/12-monkeys_tt0114746_TpGPSRGrL3s_8.461_9.483.wav", sr=44100, mono=True)

In [ ]:
from IPython.display import Audio

Audio(wav, rate=44100)

In [ ]:
fmin = 65
fmax = 1000
hop_length = 513
frame_length = 2048

frame_period = hop_length / 44100 * 1000  # ms

In [6]:
frame_period

11.63265306122449

In [4]:
import pyworld as pw
import numpy as np
f0, sp, ap = pw.wav2world(wav.astype(np.float64), 44100)

In [19]:
_f0, t = pw.dio(wav.astype(np.float64), 44100, f0_ceil=350, frame_period=frame_period )    # raw pitch extractor
f0 = pw.stonemask(wav.astype(np.float64), _f0, t, 44100)  # pitch refinement

In [9]:
len(f0)

88

In [20]:
f0[f0 > 0].mean()

159.39026327666332

In [15]:
f0[f0 > 0]

array([132.08146223, 176.51567897, 114.42732679, 181.76921335,
       195.5778217 , 250.17362639, 240.33609907, 121.80434874,
       118.89137413, 117.04921933, 113.28264192, 121.36531407,
       123.57671892, 131.14981195, 132.9253562 , 134.21725066,
       135.0629676 , 134.6847162 , 129.71980007, 132.27225311,
       132.66271958, 106.20954899, 171.69052035, 180.07484625,
       192.19839938, 134.56799433, 140.67983558, 144.79935745,
       142.18805363, 183.99502713, 180.29979806, 178.62327591,
       170.52243108, 157.31550192, 190.7913161 , 165.94723252,
       190.02446374, 184.6612285 , 177.88593588, 193.92998383,
       195.10144419, 201.26656056, 201.46284453])

In [25]:
from funasr import AutoModel
emotion_model = AutoModel(model="iic/emotion2vec_plus_large", hub="hf")

funasr version: 1.1.16.
Check update of funasr, and it would cost few times. You may disable it by set `disable_update=True` in AutoModel
New version is available: 1.2.7.
Please use the command "pip install -U funasr" to upgrade.


Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.0.0.weight, /home3/s20245649/.cache/huggingface/hub/models--emotion2vec--emotion2vec_plus_large/snapshots/6c303ba987b86b93193de93e34bb2b077a6bedc4/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.0.0.bias, /home3/s20245649/.cache/huggingface/hub/models--emotion2vec--emotion2vec_plus_large/snapshots/6c303ba987b86b93193de93e34bb2b077a6bedc4/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.1.0.weight, /home3/s20245649/.cache/huggingface/hub/models--emotion2vec--emotion2vec_plus_large/snapshots/6c303ba987b86b93193de93e34bb2b077a6bedc4/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.1.0.bias, /home3/s20245649/.cache/huggingface/hub/models--emotion2vec--emotion2vec_plus_large/snapshots/6c303ba987b86b93193de93e34bb2b077a6bedc4/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.2.0.weight, /home3/s20245649/.cache/huggingface/hu

In [35]:
 emotion_model.generate("/data1/movie/CMD/processed_wavs/audio_segments_bef_persona/bull-durham_tt0094812_mn5crhTusSA_39.113_42.34.wav", granularity="utterance", extract_embedding=False)

rtf_avg: 0.017: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.95it/s]


[{'key': 'bull-durham_tt0094812_mn5crhTusSA_39.113_42.34',
  'labels': ['生气/angry',
   '厌恶/disgusted',
   '恐惧/fearful',
   '开心/happy',
   '中立/neutral',
   '其他/other',
   '难过/sad',
   '吃惊/surprised',
   '<unk>'],
  'scores': [2.8706926968879998e-06,
   7.668742000532802e-06,
   8.446370884485077e-06,
   7.164012640714645e-05,
   6.365306035149843e-05,
   1.0373929363108325e-12,
   0.0003564004728104919,
   0.999489426612854,
   1.3907739404572794e-09]}]

In [113]:
    f0, voiced_flag, _= librosa.pyin(
                wav, 
                fmin=65, 
                fmax=400,
                sr=44100,
                hop_length=513,
                frame_length=2048
                )

In [115]:
voiced_flag

array([False,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True])

In [116]:
f0[voiced_flag]

array([121.2942889 , 119.90110517, 119.90110517, 119.90110517,
       119.90110517, 115.81683336, 133.80929076, 133.80929076,
       133.80929076, 133.80929076, 133.80929076, 122.70366065,
       121.2942889 , 119.90110517, 116.48775345, 119.90110517,
       121.99693957, 127.0307959 , 129.2512551 , 132.27235997,
       133.80929076, 134.5844401 , 134.5844401 , 133.03860596,
       130.75308234, 136.14823597,  99.09230651,  99.09230651,
        97.38996   ,  94.61745688,  91.39443896,  87.7727465 ,
        86.26486325,  85.27402679,  84.29457105,  83.80907005,
        83.32636532,  82.84644078,  83.32636532,  86.76459052,
        88.79261669,  88.79261669,  87.7727465 ,  84.29457105,
        83.80907005,  84.29457105,  84.78288453,  85.27402679,
        85.7680142 ,  86.26486325,  85.7680142 ,  96.8290351 ,
        97.38996   ,  97.9541343 ,  98.52157682,  98.52157682,
        98.52157682,  97.9541343 ])

In [97]:
len(f0)

88

In [117]:
f0[voiced_flag].mean()

106.48432505947197

In [3]:
from AutomaticPipeline.VoiceGenderClassifier import ECAPA_gender

In [4]:
model = ECAPA_gender.from_pretrained("JaesungHuh/voice-gender-classifier")
model.eval()

config.json:   0%|          | 0.00/15.0 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/61.9M [00:00<?, ?B/s]

ECAPA_gender(
  (conv1): Conv1d(80, 1024, kernel_size=(5,), stride=(1,), padding=(2,))
  (relu): ReLU()
  (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layer1): Bottle2neck(
    (conv1): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
    (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (convs): ModuleList(
      (0-6): 7 x Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
    )
    (bns): ModuleList(
      (0-6): 7 x BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (conv3): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
    (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU()
    (se): SEModule(
      (se): Sequential(
        (0): AdaptiveAvgPool1d(output_size=1)
        (1): Conv1d(1024, 128, kernel_size=(1,), stride=(1,))
        (2): ReLU()
        (3): Conv1d(128, 

In [6]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

ECAPA_gender(
  (conv1): Conv1d(80, 1024, kernel_size=(5,), stride=(1,), padding=(2,))
  (relu): ReLU()
  (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layer1): Bottle2neck(
    (conv1): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
    (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (convs): ModuleList(
      (0-6): 7 x Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
    )
    (bns): ModuleList(
      (0-6): 7 x BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (conv3): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
    (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU()
    (se): SEModule(
      (se): Sequential(
        (0): AdaptiveAvgPool1d(output_size=1)
        (1): Conv1d(1024, 128, kernel_size=(1,), stride=(1,))
        (2): ReLU()
        (3): Conv1d(128, 

In [9]:
example_file = "/data1/movie/CMD/processed_wavs/audio_segments_bef_persona/48-hrs._tt0083511_7msu2ugXGW8_78.013_80.86.wav"
with torch.no_grad():
    output = model.predict(example_file, device=device)
    print(output)

male
